# Generated by Django 4.0.4 on 2022-06-19 14:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='create_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
